features(common):User Interface for Viewing Volume Items[SEM-15]
Ditmar/sem_2023_magazine_g2 pull request #1
Opened 2023-12-01 21:06 UTC by calebrian

In this interface, articles from a selected volume are displayed.

2023-12-04 03:21 UTC, Ditmar commented on src/app/page.tsx
> +                                          <path d="M3.56272 50.0594C4.49379 46.3488 5.40484 42.7632 6.27455 39.167C6.35458 38.8345 6.28655 38.3584 6.09447 38.0831C3.18523 33.9097 1.92469 29.2867 2.23
SVGs and Accessibility Consider extracting SVGs into separate components or using an image asset management library.

2023-12-04 03:22 UTC, Ditmar commented on src/app/page.tsx
> +                                  <path d="M6.75642 17.0086C6.75642 16.2558 6.7616 15.503 6.75297 14.7511C6.75125 14.5744 6.8004 14.5248 6.97631 14.5283C7.57044 14.5396 8.16543 14.5266 8.76043 14.535
SVGs and Accessibility Consider extracting SVGs into separate components or using an image asset management library.

2023-12-07 10:49 UTC, olmedo90 commented
![image](https://github.com/Ditmar/sem_2023_magazine_g2/assets/77794323/b0ba5cd1-4a6e-4648-b92d-51e6f6ad5642)

It is according to the figma. continue with the same interest. 👍

2023-12-10 05:02 UTC, Ditmar requested changes
Good improvements, only two comments please check it

2023-12-10 05:02 UTC, Ditmar commented on src/components/Articles/index.tsx
> +                    <div key={articles.id} className="">
Ok, create another component for every item of the component in a separate file.

2023-12-10 05:02 UTC, Ditmar commented on src/components/Articles/scss/mystile.scss
> +@import url('https://fonts.googleapis.com/css2?family=Roboto&display=swap');
Please read this article of the next documentation to use to optimize fonts for next 13 https://nextjs.org/docs/pages/building-your-application/optimizing/fonts

2023-12-12 00:30 UTC, Ditmar requested changes

2023-12-12 00:30 UTC, Ditmar commented on src/app/async/api.ts
> +        const response = await fetch('https://jsonplaceholder.typicode.com/comments');
ok is good but please don't use directly the URL you need to pass that as a parameter 
```
export const fetchData = async (URL: string): Promise<Article[]> => {
    try {
        const response = await fetch(URL);
        ...
```
and you can use it as follows
```
fetchData (`process.env.BASE_API_URL/${service}`)
```
this is only an example you need to made changes based in your requirements

2023-12-13 14:45 UTC, Ditmar approved these changes
approved

2023-12-13 16:07 UTC, merged