Feature/sem 3 g2
Ditmar/sem_2023_magazine_g2 pull request #13
Opened 2023-12-07 21:35 UTC by Vecc2424

frontend for Access and Sharing of Scientific Articles [SEM-3]

2023-12-08 09:29 UTC, olmedo90 commented
![image](https://github.com/Ditmar/sem_2023_magazine_g2/assets/77794323/86349949-3e15-41dc-863e-6b08ee0a2fbd)

It is according to the figma, continue with the same interest. 👍👍👍

2023-12-10 04:45 UTC, Ditmar requested changes

2023-12-10 04:45 UTC, Ditmar commented on package.json
> +    "react-syntax-highlighter": "^15.5.0",
Why you need to install `react-syntax-highlighter`

2023-12-10 04:45 UTC, Ditmar commented on src/app/apiconection/api.ts
> +        const response = await fetch('https://jsonplaceholder.typicode.com/comments');
ok , this is not good you need to separate the request in another file, you can create another directory called Async, and there you can create an API request service.
```
type RequestParams = {
    method: string;
    headers?: HeadersInit;
    body?: BodyInit | null;
};

type FetchOptions = {
    responseType: 'json' | 'blob';
};

async function fetchService<T>(
    url: string, 
    params: RequestParams, 
    options: FetchOptions
): Promise<T> {
    try {
        const response = await fetch(url, params);

        if (!response.ok) {
            throw new Error(`HTTP error! Status: ${response.status}`);
        }

        return options.responseType === 'json' ? await response.json() : await response.blob();
    } catch (error) {
        console.error('Fetching error:', error);
        throw error;
    }
}

async function getJsonData<T>(url: string): Promise<T> {
    return fetchService<T>(url, { method: 'GET' }, { responseType: 'json' });
}

// Example usage for Blob (file)
async function getFile(url: string): Promise<Blob> {
    return fetchService<Blob>(url, { method: 'GET' }, { responseType: 'blob' });
}

export { getJsonData, getFile };
```
And how to use it.
Suppose you have an API endpoint that returns user data in JSON format. You want to fetch this data and display it. Here's how you can use the getJsonData **function:**

```
import { getJsonData } from './fetchService'; 

interface UserData {
    id: number;
    name: string;
    email: string;
    // ... other user fields
}

async function fetchUserData() {
    try {
        const url = 'https://example.com/api/users'; 
        const userData = await getJsonData<UserData[]>(url);
        console.log('User Data:', userData);
        // Process and display the user data as needed
    } catch (error) {
        console.error('Error fetching user data:', error);
    }
}

// Call this function where you need to fetch the user data
fetchUserData();
```
please take this approach and refactor your code

2023-12-10 04:45 UTC, Ditmar commented on src/app/page.tsx
> +      <ArticulosCietificos/>
User english for the name of your components example ScientificArticles

2023-12-10 04:45 UTC, Ditmar commented on src/app/apiconection/api.ts
> +        const response = await fetch('https://jsonplaceholder.typicode.com/comments');
dont hard code the urls use the envs. process.env.SOME_URL

2023-12-10 04:45 UTC, Ditmar commented on src/components/ArticulosCientificos/index.tsx
> +              <p className="article-recent">ARTÍCULOS MAS RECIENTES</p>
divide all this code in most small components

2023-12-10 04:45 UTC, Ditmar commented on src/components/ArticulosCientificos/styles.scss
> +@import url('https://fonts.googleapis.com/css2?family=Roboto&display=swap');
read this article to improve the approach for importing the fonts https://nextjs.org/docs/pages/building-your-application/optimizing/fonts

2023-12-12 00:25 UTC, Ditmar approved these changes
good job

2023-12-12 16:50 UTC, Ditmar approved these changes

2023-12-12 17:43 UTC, Ditmar approved these changes

2023-12-12 17:43 UTC, merged